# NOTE: the loop_control sets the iteration variable name from item to site_name because the inner loops in the playbooks already are using item 
# we do this to avoid conflicting issues on the inner loops!
---
- hosts: localhost
  connection: local
  tasks:
# Variable file inclusion section
    - name: include variables
      include_vars: 
        file: "ansible variables/site_list.yml"
        name: site_list
        
#### Here is where we get into MSO config ####
    - name: build MSO site in the MSO controller
      include: mso_site_add.yml
      vars:
        APIC: "{{ site_name }}"
      with_items: "{{ site_list['SITE_LIST'] }}"
      loop_control:
        loop_var: site_name