---
- hosts: mso_leader
  gather_facts: false
  
  vars:
    ansible_user: root
    ansible_ssh_pass: PASSWORD
#    ansible_python_interpreter: venv/bin/python
    docker_swarm_gather_token: 'docker swarm  join-token manager | egrep -o "SWMTK.* ([0-9]{1,3}\.){3}[0-9]{1,3}"'
    
  tasks:
# Set VM hostname to meet Cisco requirements.  This must be properly set in inventory file    
  - name: Set system hostname
    hostname:
      name: "{{ inventory_hostname }}"
      
# Get version of the build to use for full path of script
  - name: Get MSO version
    command: "ls /opt/cisco/msc/builds/"
    register: mso_version
    
# Setup the docker swarm using the provided script on the leader   
  - name: initialize the docker swarm
    shell: "/opt/cisco/msc/builds/{{ mso_version.stdout }}/prodha/msc_cfg_init.py"
    
# Swarm builds then we get the output we need
  - name: get token to join followers
    shell: "{{ docker_swarm_gather_token }}"
    register: swarm_leader_output
    
# Copy the output of the command to a file to be used by the followers    
  - name: copy output to file
    copy:
      content: "value: {{ swarm_leader_output.stdout }}"
      dest: "swarm_leader_output.json"
    delegate_to: localhost
