---
- name: Update Admin password
  hosts: node1
  gather_facts: False

  vars_prompt:
     # This is the current password by default the password will usually be We1come! or We1come2msc!
   - name: "current_password"
     prompt: "Enter the current admin password - Password will usually be We1come! or We1come2msc!"
     # This is the password you wish to update to
   - name: "new_password"
     prompt: "Enter new admin password"

  tasks:
   - name: Update Admin password
     mso_user:
       host: "{{ ansible_host }}"
       username: admin
       password: "{{ current_password }}"
       user: admin
       user_password: "{{ new_password }}"
       state: present
       account_status: active
       use_ssl: yes
       validate_certs: no
     delegate_to: localhost